# -*- coding: utf-8 -*-
"""script_pdf_to_txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aURVOywTRDQ3M1yaxTalZgu8oEc-Ic7
"""

pip install pdfplumber

import pdfplumber
import os

def converter_pdf_para_txt(pasta_entrada, pasta_saida):
    if not os.path.exists(pasta_saida):
        os.makedirs(pasta_saida)

    for nome_arquivo in os.listdir(pasta_entrada):
        if nome_arquivo.lower().endswith(".pdf"):
            caminho_pdf = os.path.join(pasta_entrada, nome_arquivo)
            nome_base = os.path.splitext(nome_arquivo)[0]
            caminho_txt = os.path.join(pasta_saida, f"{nome_base}.txt")

            try:
                with pdfplumber.open(caminho_pdf) as pdf:
                    texto_completo = ""
                    for pagina in pdf.pages:
                        texto_completo += pagina.extract_text() + "\n"

                with open(caminho_txt, "w", encoding="utf-8") as f:
                    f.write(texto_completo)
                print(f"Convertido: {nome_arquivo} -> {nome_base}.txt")
            except Exception as e:
                print(f"Erro ao processar {nome_arquivo}: {e}")

pasta_origem_pdfs = "/content/drive/MyDrive/planos_gov_cand_mun/2024_pdf"
pasta_destino_txts = "/content/drive/MyDrive/planos_gov_cand_mun/2024_txt"

converter_pdf_para_txt(pasta_origem_pdfs, pasta_destino_txts)